routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::put('/public/{id}', 'QueueController@updatephone');

Route::get('/coba', 'QueueController@coba');

Route::get('/public/{id?}', 'QueueController@indexCustomer');

Route::get('/event',function(){
    event(new App\Events\Event("hallo"));
});

Route::Group(['middleware'=>'auth'],function(){
    Route::resource('/queue', 'QueueController');
    Route::post('/reset', 'QueueController@reset');
    Route::resource('/group', 'GroupController');
    Route::resource('/videos', 'VideoController');
    Route::resource('/admin', 'UserController');
    Route::resource('/setting', 'SettingController');
    Route::get('/android', 'SettingController@android');
    Route::resource('/report', 'ReportController');
    Route::get('/configure', 'SettingController@configure');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Setting.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    //
}

app/Http/Controllers/SettingController.php
<?php

namespace App\Http\Controllers;
use App\Setting;
use Illuminate\Http\Request;

class SettingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function configure(){
        $setting=Setting::All();
        return view('settings.configure',compact('setting'));
    }
    public function web()
    {
        $setting=Setting::All();
        return view('settings.index',compact('setting'));
    }
    public function android()
    {
        $setting=Setting::All();
        return view('settings.android',compact('setting'));
    }
    public function index()
    {
        $setting=Setting::All();
        return view('settings.index',compact('setting'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if($id==0){
            $setting=Setting::where('id','<','9')->get();
            $i=1;
        }
        else if($id==1){
            $setting=Setting::where('id','>=','9')->where('id','<',25)->get();
            $i=9;    
        }
        else if($id==2){
            $setting=Setting::where('id','>=','25')->get();
            $i=25;
        }
        foreach($setting as $s){
            $a="set".$i;
            $s->description=$request->$a;
            $i++;
            if ($s->description=="" && ($i==7 || $i==16)){
                continue;
            }
            if ($i==7 || $i==16){
                $file = $request->file($a);
                $filename = $file->getClientOriginalName();
                $s->description=$filename;
                $path = public_path().'/picture/';
                $file->move($path,$filename);
            }
            $s->save();
        }
        return redirect("/queue");

    }

    public function getSetting(Request $request){
        $setting=Setting::where('id','<=','14')->Get();
        return $setting;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/settings/android.blade.php
@extends('includes.main')
@section('head')
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
@stop
@section('path')
<h1>
  Interface
  <small>Manage Interface</small>
</h1>
<ol class="breadcrumb">
  <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
  <li><a href="#">Interface</a></li>
  <li class="active">Data tables</li>
</ol>
@stop
@section('content')
<div class="col-sm-8 col-sm-offset-2">
  <!-- general form elements -->
  <div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Android Interface</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start --> 
    <form action="{{route('setting.update',0)}}" method="POST"  enctype="multipart/form-data">
      <div class="box-body">
        <div class=col-sm-6>
          <label>Warna Background</label>
          <div id="cp1" class="input-group colorpicker-component">
            <input type="text" class="form-control input-lg" value={{$setting[0]->description}} name="set1" />
            <span class="input-group-addon"><i></i></span>
          </div>
          <label>Warna Button Gradasi 1</label>
          <div id="cp1" class="input-group colorpicker-component">
            <input type="text" class="form-control input-lg" value={{$setting[1]->description}} name="set2" />
            <span class="input-group-addon"><i></i></span>
          </div>
          <label>Warna Button Gradasi 2</label>
          <div id="cp1" class="input-group colorpicker-component">
            <input type="text" class="form-control input-lg" value={{$setting[2]->description}} name="set3">
            <span class="input-group-addon"><i></i></span>
          </div>
        </div>
        <div class="col-sm-6">
          <label>Warna Background Input</label>
          <div id="cp1" class="input-group colorpicker-component">
            <input type="text" class="form-control input-lg" value={{$setting[3]->description}} name="set4">
            <span class="input-group-addon"><i></i></span>
          </div>
          <label>Warna Font</label>
          <div id="cp1" class="input-group colorpicker-component">
            <input type="text" class="form-control input-lg" value={{$setting[4]->description}} name="set5">
            <span class="input-group-addon"><i></i></span>
          </div>
        </div>
        <div class="col-sm-12">
          <label>Logo Restoran</label>
          <input type="file" class="form-control" value={{$setting[5]->description}} name="set6">
          <label>Current Logo</label><br>
          @if($setting[5]->description=="")
          Nothing to display.<br>
          @else
          <img src="{{URL::asset('picture/'.$setting[5]->description)}}" style="width:10vw;height:10vh;" alt="Can not load">
          <br>
          @endif
          <label>Keterangan</label>
          <textarea class="form-control" name="set7" style="resize:none;" required>{{$setting[6]->description}}</textarea>
          <label>Struk</label>
          <textarea class="form-control" name="set8" style="resize:none;" required>{{$setting[7]->description}}</textarea>
        </div>
      </div>
      <div class="box-footer">
        <div class="form group col-sm-12">
          <input type="hidden" name="_method" value="PUT">
          <input type="hidden" name="_token" value="{{ csrf_token() }}">
          <button type="submit" class="btn pull-right myButton1" > Save changes</button>
        </div>
      </div>
    </form>
  </div>
</div>
@stop
@section('foot')

<script>
  $(function () {
    $('#cp1,#cp2').colorpicker({
      autoInputFallback: false
    });
  });
</script>
<script type="text/javascript">
  $(function() {
    document.getElementById("settingPage").className += " active";
  });
</script>

<script>
  $(function () {
    $('#cp13').colorpicker({
      autoInputFallback: false
    });
  });
</script>
<!--<script src="../../bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="../../bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
<script>
$(function () {
  $('#example1').DataTable()
  $('#example2').DataTable({
    'paging'      : true,
    'lengthChange': false,
    'searching'   : false,
    'ordering'    : true,
    'info'        : true,
    'autoWidth'   : false
    })
  })
</script>-->
@stop

resources/views/settings/configure.blade.php
@extends('includes.main')
@section('head')

<link rel="stylesheet" href="../../bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
@stop
@section('path')
<h1>
  Configuration
  <small>Manage Configuration</small>
</h1>
<ol class="breadcrumb">
  <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
  <li><a href="#">Configuration</a></li>
  <li class="active">Data tables</li>
</ol>
@stop
@section('content')
<div class="col-sm-8 col-sm-offset-2">
  <!-- general form elements -->
  <div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Queue Form</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    <form action='/reset' method='POST'>
      <div class="box-body">
        <div class="form group col-sm-12" style="margin-top: 20px">
          <label>Reset Queue Number</label>
          
          <input type="hidden" name="_token" value="{{ csrf_token() }}">
          <button type="submit" class="btn btn-danger pull-right" > Reset</button>
        </div>
      </div>
    </form>
  </div>
  <div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Twilio Form</h3>
    </div>
    <form action="{{route('setting.update',2)}}" method='POST'>
      <div class="box-body">
        <div class="form group col-sm-12">
          <label>Twilio SID</label>
          <input class="form-control" type='text' name="set25" required value={{$setting[24]->description}}>
        </div>
        
        <div class="form group col-sm-12">
          <label>Twilio Token</label>
          <input class="form-control" type='text' name='set26' required value={{$setting[25]->description}}>
        </div>
        
        <div class="form group col-sm-12">
          <label>Twilio Number</label>
          <input class="form-control" type='text' name='set27' required value={{$setting[26]->description}}>
        </div>
        <div class="form group col-sm-12">
          <label>Message</label>
          <textarea class="form-control" id="text" name="set28" placeholder="Type in your message" rows="2" style="resize: none">{{$setting[27]->description}}</textarea>
          <h6 class="pull-right" id="count_message"></h6>
          <h6 class="pull-right">[number] untuk nomer antrian |</h6>
        </div>
      </div>
      <div class="box-footer">
        <div class="form group col-sm-12">
          <input type="hidden" name="_method" value="PUT">
          <input type="hidden" name="_token" value="{{ csrf_token() }}">
          <button type="submit" class="btn pull-right myButton1" > Save changes</button>
        </div>
      </div>
    </form>
  </div>
</div>
@stop
@section('foot')
<script type="text/javascript">
  $(function() {
    document.getElementById("settingPage").className += " active";
  });
  
  var text_max = 160;
  $('#count_message').html(text_max + ' remaining');
  
  $('#text').keyup(function() {
    var text_length = $('#text').val().length;
    var text_remaining = text_max - text_length;
    
    $('#count_message').html(text_remaining + ' remaining');
  });
</script>
<!--<script src="../../bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
  <script src="../../bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
  <script>
    $(function () {
      $('#example1').DataTable()
      $('#example2').DataTable({
        'paging'      : true,
        'lengthChange': false,
        'searching'   : false,
        'ordering'    : true,
        'info'        : true,
        'autoWidth'   : false
      })
    })
  </script>-->
  @stop

resources/views/settings/index.blade.php
@extends('includes.main')
@section('path')
<h1>
    Interface
    <small>Manage Interface</small>
</h1>
<ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="#">Interface</a></li>
    <li class="active">Data tables</li>
</ol>
@stop
@section('content')
<div class="col-sm-8 col-sm-offset-2">
    <!-- general form elements -->
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">Web Interface</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start --> 
        <form action="{{route('setting.update',1)}}" method="POST"  enctype="multipart/form-data">
            <div class="box-body">
                <div class="col-sm-12">
                    <label>Nama Restoran</label>
                    <textarea class="form-control" name="set14" style="resize:none;" required>{{$setting[13]->description}}</textarea>
                    
                    <label>Banner Restoran</label>
                    <input type="file" class="form-control" value={{$setting[14]->description}} name="set15">
                    <label>Current Banner</label><br>
                    @if($setting[14]->description=="")
                    Nothing to display.<br>
                    @else
                    <img src="{{URL::asset('picture/'.$setting[14]->description)}}" style="width:10vw;height:10vh;" alt="Can not load">
                    @endif
                </div>
                
                <div class=col-sm-6>
                    <label>Navbar</label>
                    <div id="cp1" class="input-group colorpicker-component">
                        <input type="text" class="form-control input-lg" value={{$setting[8]->description}} name="set9">
                        <span class="input-group-addon"><i></i></span>
                    </div>
                    <label>Background</label>
                    <div id="cp1" class="input-group colorpicker-component">
                        <input type="text" class="form-control input-lg" value={{$setting[9]->description}} name="set10">
                        <span class="input-group-addon"><i></i></span>
                    </div>
                    <label>Warna Blinking Queue</label>
                    <div id="cp1" class="input-group colorpicker-component">
                        <input type="text" class="form-control input-lg" value={{$setting[23]->description}} name="set24">
                        <span class="input-group-addon"><i></i></span>
                    </div>
                    <label>Background Group 1</label>
                    <div id="cp1" class="input-group colorpicker-component">
                        <input type="text" class="form-control input-lg" value={{$setting[15]->description}} name="set16">
                        <span class="input-group-addon"><i></i></span>
                    </div>
                    <label>Background Group 2</label>
                    <div id="cp1" class="input-group colorpicker-component">
                        <input type="text" class="form-control input-lg" value={{$setting[16]->description}} name="set17">
                        <span class="input-group-addon"><i></i></span>
                    </div>
                    <label>Background Group 3</label>
                    <div id="cp1" class="input-group colorpicker-component">
                        <input type="text" class="form-control input-lg" value={{$setting[17]->description}} name="set18">
                        <span class="input-group-addon"><i></i></span>
                    </div>
                    <label>Background Group 4</label>
                    <div id="cp1" class="input-group colorpicker-component">
                        <input type="text" class="form-control input-lg" value={{$setting[18]->description}} name="set19">
                        <span class="input-group-addon"><i></i></span>
                    </div>
                </div>
                <div class=col-sm-6>
                    <label>Button</label>
                    <div id="cp1" class="input-group colorpicker-component">
                        <input type="text" class="form-control input-lg" value={{$setting[10]->description}} name="set11">
                        <span class="input-group-addon"><i></i></span>
                    </div>
                    <label>Font</label>
                    <div id="cp1" class="input-group colorpicker-component">
                        <input type="text" class="form-control input-lg" value={{$setting[11]->description}} name="set12">
                        <span class="input-group-addon"><i></i></span>
                    </div>
                    <label>Panel</label>
                    <div id="cp1" class="input-group colorpicker-component">
                        <input type="text" class="form-control input-lg" value={{$setting[12]->description}} name="set13">
                        <span class="input-group-addon"><i></i></span>
                    </div>
                    <label>Font Group 1</label>
                    <div id="cp1" class="input-group colorpicker-component">
                        <input type="text" class="form-control input-lg" value={{$setting[19]->description}} name="set20">
                        <span class="input-group-addon"><i></i></span>
                    </div>
                    <label>Font Group 2</label>
                    <div id="cp1" class="input-group colorpicker-component">
                        <input type="text" class="form-control input-lg" value={{$setting[20]->description}} name="set21">
                        <span class="input-group-addon"><i></i></span>
                    </div>
                    <label>Font Group 3</label>
                    <div id="cp1" class="input-group colorpicker-component">
                        <input type="text" class="form-control input-lg" value={{$setting[21]->description}} name="set22">
                        <span class="input-group-addon"><i></i></span>
                    </div>
                    <label>Font Group 4</label>
                    <div id="cp1" class="input-group colorpicker-component">
                        <input type="text" class="form-control input-lg" value={{$setting[22]->description}} name="set23">
                        <span class="input-group-addon"><i></i></span>
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <div class="form group col-sm-12">
                    <input type="hidden" name="_method" value="PUT">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    <button type="submit" class="btn pull-right myButton1" > Save changes</button>
                </div>
            </div>
        </form>
    </div>
</div>
@stop
@section('foot')
<script>
    $(function () {
        $('#cp1,#cp2').colorpicker({
            autoInputFallback: false
        });
    });
</script>

<script type="text/javascript">
    function yaya(){
        alert("ha");
    }
    $(function() {
        document.getElementById("settingPage").className += " active";
    });

</script>
<!--<script src="../../bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="../../bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script>
        $(function () {
            $('#example1').DataTable()
            $('#example2').DataTable({
                'paging'      : true,
                'lengthChange': false,
                'searching'   : false,
                'ordering'    : true,
                'info'        : true,
                'autoWidth'   : false
            })
        })
    </script>-->
    @stop